{
 "title": "STOCK DATA",
 "description": "Score 1 = Stock will go up (High)\nScore 0 = Stock will be same (Neutral)\nScore -1 = Stock will go down (Low)",
 "time": { "from": "2023-12-04T22:25:16.355Z", "to": "2023-12-05T04:25:16.356Z" },
 "templating": {
  "list": [
   {
    "name": "Stock_Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Score 1 = Stock will go up (High)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Score 0 = Stock will be same (Neutral)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Score -1 = Stock will go down (Low) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Sentiment to Stock Price ",
   "type": "barchart",
   "description": "Score 1 = Stock will go up (High)\nScore 0 = Stock will be same (Neutral)\nScore -1 = Stock will go down (Low)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "panoply-b19-9e8056de8e7a",
     "rawSql": "SELECT\n  FORMAT_DATE('%Y-%m-%d', date) AS Stock_date,\n  (SUM(CAST(closing_price AS FLOAT64)) / COUNT(closing_price)) AS Closing_Price,\n  (SUM(sentiment_inference) / COUNT(sentiment_inference) )  sentiment_inference\nFROM\n  `panoply-b19-9e8056de8e7a.panoply.dynamo_tbl_redditstocksentiment`\nWHERE\n  stock_ticker = '$Stock_Name'\nGROUP BY\n  Stock_date\nORDER BY\n  Stock_date"
    }
   ]
  },
  {
   "title": "Accurate Stock Price",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "repeat": "Stock_Name",
   "targets": [
    {
     "dataset": "panoply",
     "location": "US",
     "project": "panoply-b19-9e8056de8e7a",
     "rawSql": "SELECT\n  FORMAT_DATE('%Y-%m-%d', date) AS Stock_date,\n  (SUM(CAST(closing_price AS FLOAT64)) / COUNT(closing_price)) AS Closing_Price,\n  CASE\n    WHEN (SUM(sentiment_inference) / COUNT(sentiment_inference) > 0) THEN \"POSITIVE\"\n    WHEN (SUM(sentiment_inference) / COUNT(sentiment_inference) < 0) THEN \"NEGATIVE\"\n    ELSE \"NEUTRAL\"\n  END AS sentiment_inference\nFROM\n  `panoply-b19-9e8056de8e7a.panoply.dynamo_tbl_redditstocksentiment`\nWHERE\n  stock_ticker = '$Stock_Name'\nGROUP BY\n  Stock_date\nORDER BY\n  Stock_date"
    }
   ]
  },
  {
   "title": "Sentiment Inference Score ",
   "type": "gauge",
   "description": "Score 1 = Stock will go up (High)\nScore 0 = Stock will be same (Neutral)\nScore -1 = Stock will go down (Low)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "panoply",
     "location": "US",
     "project": "panoply-b19-9e8056de8e7a",
     "rawSql": "SELECT\n  (SUM(sentiment_inference) / (\n    SELECT COUNT(sentiment_inference)\n    FROM `panoply-b19-9e8056de8e7a.panoply.dynamo_tbl_redditstocksentiment`\n    WHERE stock_ticker = '$Stock_Name'\n  )) AS sentiment_inference\nFROM `panoply-b19-9e8056de8e7a.panoply.dynamo_tbl_redditstocksentiment`\nWHERE stock_ticker = '$Stock_Name';"
    }
   ]
  }
 ]
}